
translations = {
    "Français": {
        "settings": "Paramètres",
        "language": "Langue",
        "back": "Retour",
        "back_loading": "Retour...",
        "start_game": "Lancer le jeu",
        "quit": "Quitter",
        "rules": "Règles",
        "G's_rules": "Règles du jeu",
        "validate": "Valider",
        "confirm": "Confirmer",
        "edit": "Editer",
        "board_edit": "Edition du plateau",
        "help_text": "Cliquez sur un cadrant pour le faire pivoter",
        "enter_player1": "Joueur 1 (Rouge): ",
        "enter_player2": "Joueur 2 (Bleu): ",
        "default_player1": "Joueur 1",
        "default_player2": "Joueur 2",
        "select_game": "Sélection du jeu",
        "selecting_game": "Sélection de ",
        "game_selected": "Jeu sélectionné : ",
        "game_mode": "Mode de jeu : ",
        "katarenga": "Katarenga",
        "congress": "Congress",
        "isolation": "Isolation",
        "mode_local": "Mode local (2 joueurs)",
        "mode_local_loading": "Chargement du mode local...",
        "mode_online": "Mode en ligne (à venir)",
        "mode_online_loading": "Chargement du mode en ligne...",
        "mode_bot": "Jouer contre un robot",
        "mode_bot_loading": "Chargement contre le bot...",
        "enter_names": "Entrez les noms des joueurs sans espaces ni caractères spéciaux.",
        "turn": "C'est au tour de : ",
        "win" : " à gagné !",
        "new_game": "Nouvelle Partie",
        "K's_rules": "Règles de Katarenga",
        "K's_help": "Cliquez sur un de vos pions puis sur une case valide pour le déplacer",
        "K's_Rules": [
            "Katarenga est un jeu de stratégie pour deux joueurs.",
            "Chaque joueur contrôle 8 pions qui se déplacent selon la case où ils se trouvent:",
            "",
            "Case A (Gris clair): Mouvements orthogonaux (comme une tour aux échecs)",
            "Case B (Marron): Mouvements diagonaux (comme un fou aux échecs)",
            "Case C (Vert): Mouvements en L (comme un cavalier aux échecs)",
            "Case D (Bleu acier): Mouvements dans toutes directions (comme une dame aux échecs)",
            "",
            "But du jeu: Occuper les deux camps adverses ou empêcher l'adversaire de jouer",
            "en capturant suffisamment de ses pions.",
            "",
            "Pour occuper un camp adverse :",
            "1. Amener d'abord un pion sur la ligne de base adverse",
            "2. Puis déplacer ce pion dans un camp adverse (déplacement spécial)",
            "3. Une fois dans un camp, le pion y reste jusqu'à la fin de la partie",
            "",
            "Les captures sont autorisées sauf lors du premier tour de jeu.",
            "La capture se fait en déplaçant un de ses pions sur une case occupée par un pion adverse.",
        ],
        "I's_rules": "Règles de Isolation",
        "I's_help": "Posez un pion sur une case non menacée",
        "I's_Rules": [
            "Le plateau est initialement vide.",
            "Le jeu se joue à deux joueurs.",
            "",
            "À tour de rôle, chaque joueur place un de ses pions sur une case vide du plateau.",
            "Un pion ne peut être placé que s'il n'est pas en prise, c'est-à-dire :",
            "  - Il ne doit pas pouvoir être capturé par un pion déjà présent sur le plateau",
            "    (quelle que soit sa couleur), selon les règles de capture définies pour le jeu.",
            "",
            "Il n'y a aucun déplacement ni capture pendant la partie :",
            "  - Les pions restent sur la case où ils ont été posés.",
            "",
            "Le jeu continue tant que les joueurs peuvent poser des pions selon la règle ci-dessus.",
            "",
            "Le vainqueur est le dernier joueur à avoir pu poser un pion."
        ],
        "C's_rules": "Règles du Congress",
        "C's_help": "Formez un bloc avec vos pièces",
        "C's_Rules": [
            "Congress est un jeu de stratégie pour deux joueurs.",
            "Chaque joueur contrôle 8 pions qui se déplacent selon la case où ils se trouvent :",
            "",
            "Case Rouge : Mouvements orthogonaux (comme une tour aux échecs)",
            "Case Jaune : Mouvements diagonaux (comme un fou aux échecs)",
            "Case Vert : Mouvements en L (comme un cavalier aux échecs)",
            "Case Bleu : Mouvements dans toutes directions (comme une dame aux échecs)",
            "",
            "À tour de rôle, chaque joueur déplace l'un de ses pions selon les règles de déplacement ci-dessus.",
            "Les captures sont interdites.",
            "",
            "Le but du jeu est de réunir ses 8 pions sous la forme d'un bloc connecté.",
            "Un bloc connecté est un ensemble de pions du même joueur,",
            "où chaque pion est adjacent orthogonalement (haut, bas, gauche ou droite)",
            "à au moins un autre pion du même joueur.",
            "",
            "Le premier joueur à réussir cette formation gagne la partie.",
            "Si aucun joueur ne peut plus bouger et qu'aucun bloc connecté ne peut être formé,",
            "la partie est nulle.",
        ],
        "red": " (Rouge)",
        "blue": " (Bleu)",
        "white": " (Blanc)",
        "brown": " (Marron)",
    },
    "English": {
        "settings": "Settings",
        "language": "Language",
        "back": "Back",
        "back_loading": "Going back...",
        "start_game": "Start Game",
        "quit": "Quit",
        "rules": "Rules",
        "G's_rules": "Game's rules",
        "validate": "Validate",
        "confirm": "Confirm",
        "edit": "Edit",
        "help_text": "Click on a frame to rotate it",
        "board_edit": "Editing board",
        "enter_player1": "Player 1 (Red): ",
        "enter_player2": "Player 2 (Blue): ",
        "default_player1": "Player 1",
        "default_player2": "Player 2",
        "select_game": "Game selection",
        "selecting_game": "Selecting ",
        "game_selected": "Game selected : ",
        "game_mode": "Game mode : ",
        "katarenga": "Katarenga",
        "congress": "Congress",
        "isolation": "Isolation",
        "mode_local": "Local Mode (2 players)",
        "mode_local_loading": "Local game mode is loading...",
        "mode_online": "Online Mode (coming soon)",
        "mode_online_loading": "Online game mode is loading...",
        "mode_bot": "Play against a bot",
        "mode_bot_loading": "Game mode against bot is loading...",
        "enter_names": "Enter player names without spaces or special characters.",
        "turn": "It's the turn of : ",
        "win": " has won !",
        "new_game": "New game",
        "K's_rules": "Katarenga's rules",
        "K's_help": "Click on one of your pieces and then on a valid square to move it.",
        "K's_Rules": [
            "Katarenga is a strategy game for two players.",
            "Each player controls 8 pieces that move according to the square they are on:",
            "",
            "Square A (Light Grey): Orthogonal movements (like a chess tower)",
            "Square B (Brown): Diagonal moves (like a chess bishop)",
            "Square C (Green): L-shaped moves (like a chess knight)",
            "Box D (Steel Blue): Moves in all directions (like a queen in chess)",
            "",
            "Object of the game: To occupy both opposing camps or prevent the opponent from playing",
            "by capturing enough of his pawns.",
            "",
            "To occupy an opponent's camp:",
            "1. First bring a pawn onto the opponent's baseline",
            "2. Then move this piece into an opponent's camp (special move)",
            "3. Once in a camp, the piece stays there until the end of the game",
            "",
            "Captures are allowed except during the first turn of the game",
            "A capture is made by moving one of your pieces onto a square occupied by an opponent's piece",
        ],
        "I's_rules": "Isolation's rules",
        "I's_help": "Place a pawn on an unthreatened square",
        "I's_Rules": [
            "The board is initially empty.",
            "The game is played by two players.",
            "",
            "In turn, each player places one of his pieces on an empty square on the board.",
            "A piece may only be placed if it is not captured, i.e.:",
            " - It must not be possible for it to be captured by a piece already on the board.",
            " (whatever its colour), according to the capture rules defined for the game. ",
            "",
            "There are no moves or captures during the game:",
            " - The pieces remain on the square where they were placed.",
            "",
            "The game continues as long as the players can place pieces according to the above rule.",
            "",
            "The winner is the last player to be able to place a piece."
        ],
        "C's_rules": "Congress's rules",
        "C's_help": "Form a block with your pieces",
        "C's_Rules": [
            "Congress is a strategy game for two players. ",
            "Each player controls 8 pieces which move according to the square they are on:",
            "",
            "Red square: Orthogonal movements (like a chess rook)",
            "Yellow square: Diagonal movements (like a chess bishop)",
            "Green square: L-shaped movements (like a chess knight)",
            "Blue square: Movements in all directions (like a chess queen)",
            "",
            "Each player in turn moves one of his pieces according to the above movement rules. ",
            "Captures are forbidden.",
            "",
            "The object of the game is to unite all 8 checkers into a connected block.",
            "A connected block is a set of checkers from the same player,",
            "where each checker is orthogonally adjacent (top, bottom, left or right)",
            "to at least one other checker from the same player. ",
            "",
            "The first player to complete this formation wins the game.",
            "If no player can move and no connected block can be formed,",
            "the game is drawn.",
        ],
        "red": " (Red)",
        "blue": " (Blue)",
        "white": " (White)",
        "brown": " (Brown)",
    }
}

settings = {
    "language": "Français",
}

current_language = settings["language"]

def set_language(lang):
    global current_language, settings
    current_language = lang
    settings["language"] = lang
    save_settings(settings)

def save_settings(updated_settings):
    global settings, current_language
    settings.update(updated_settings)
    current_language = settings["language"]

def t(key):
    return translations.get(current_language, {}).get(key, key)
